remove useless fix param deliver
opensourceways/xihe-script pull request #55
Opened 2023-10-31 12:24 UTC by drizzlezyk

2023-10-31 12:36 UTC, zengchen1024 requested changes

2023-10-31 12:36 UTC, zengchen1024 commented on infrastructure/score/score.go
> +	data = []byte(c)
c本来就是[]byte，无需转换

2023-10-31 12:36 UTC, zengchen1024 commented on infrastructure/score/score.go
> +	args := []string{"python3", s.evaluate, "--pred_path", col.Path, "--true_path", col.AnswerPath, "--cls", strconv.Itoa(col.Cls), "--pos", strconv.Itoa(col.Pos)}
args := []string{
"python3", s.evaluate, 
"--pred_path", col.Path, 
"--true_path", col.AnswerPath, 
"--cls", strconv.Itoa(col.Cls), 
"--pos", strconv.Itoa(col.Pos)
}

适当换行，使得代码有更好的可读性

2023-10-31 12:36 UTC, zengchen1024 commented on infrastructure/score/score.go
> +	b.Write([]byte(input))
b:=bytes.NewBuffer([]byte(fmt.Sprintf(
"%s+%s+%s+%s\n", 
cfg.AccessKey, cfg.SecretKey, cfg.Bucket, cfg.Endpoint
)))

简化代码

2023-11-01 02:46 UTC, pkking commented on main.go
> +		evaluate: app.NewEvaluateService(score.NewEvaluateScore(os.Getenv("EVALUATE")), cfg),
现在xihe-script已经没有`EVALUATE`这个环境变量了，功能是否正常

2023-11-01 05:59 UTC, merged